"""add is_admin and is_confirmed fields in user model

Revision ID: 15e78fc58cc2
Revises: 9599ee453ffa
Create Date: 2024-05-22 11:18:02.603251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15e78fc58cc2'
down_revision = '9599ee453ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False))
        batch_op.drop_index('username')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
